/**
 * This file was auto-generated by scripts/generate-dtos.ts from openapi.yaml.
 * Do not make direct changes to this file.
 *
 * Requires peer dependencies: class-validator, class-transformer
 */

import { IsArray, IsBoolean, IsDateString, IsIn, IsNumber, IsObject, IsOptional, IsString, ValidateNested } from 'class-validator';
import { Type } from 'class-transformer';

export class ErrorDto {
  @IsString()
  error!: string;

}

export class SuccessResponseDto {
  @IsBoolean()
  success!: boolean;

}

export class AuthUserDto {
  @IsString()
  uid!: string;

  @IsOptional()
  @IsString()
  email?: string | null;

  @IsOptional()
  @IsString()
  displayName?: string | null;

  @IsOptional()
  @IsString()
  photoURL?: string | null;

  @IsBoolean()
  emailVerified!: boolean;

  @IsBoolean()
  isAnonymous!: boolean;

}

export class SessionResponseDto {
  @IsBoolean()
  authenticated!: boolean;

  @IsOptional()
  @ValidateNested()
  @Type(() => AuthUserDto)
  user?: AuthUserDto;

}

export class OAuthTokenRequestDto {
  @IsIn(['authorization_code', 'refresh_token', 'api_token'])
  grant_type!: 'authorization_code' | 'refresh_token' | 'api_token';

  @IsOptional()
  @IsString()
  code?: string;

  @IsOptional()
  @IsString()
  redirect_uri?: string;

  @IsOptional()
  @IsString()
  code_verifier?: string;

  @IsOptional()
  @IsString()
  refresh_token?: string;

  @IsOptional()
  @IsString()
  client_id?: string;

  @IsOptional()
  @IsString()
  client_secret?: string;

  @IsOptional()
  @IsString()
  api_token?: string;

}

export class OAuthTokenResponseDto {
  @IsString()
  access_token!: string;

  @IsIn(['bearer'])
  token_type!: 'bearer';

  @IsNumber()
  expires_in!: number;

  @IsOptional()
  @IsString()
  refresh_token?: string;

  @IsOptional()
  @IsString()
  scope?: string;

}

export class MemoryDto {
  @IsString()
  id!: string;

  @IsString()
  title!: string;

  @IsString()
  content!: string;

  @IsString()
  author_id!: string;

  @IsIn(['personal', 'group', 'public'])
  scope!: 'personal' | 'group' | 'public';

  @IsOptional()
  @IsString()
  group_id?: string | null;

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  tags?: string[];

  @IsOptional()
  @IsNumber()
  rating?: number | null;

  @IsOptional()
  @IsNumber()
  significance?: number | null;

  @IsOptional()
  @IsDateString()
  created_at?: string;

  @IsOptional()
  @IsDateString()
  updated_at?: string;

}

export class ConversationDto {
  @IsString()
  id!: string;

  @IsIn(['dm', 'group'])
  type!: 'dm' | 'group';

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  participants?: string[];

  @IsOptional()
  @IsString()
  last_message?: string | null;

  @IsOptional()
  @IsNumber()
  unread_count?: number;

  @IsOptional()
  @IsDateString()
  created_at?: string;

  @IsOptional()
  @IsDateString()
  updated_at?: string;

}

export class MessageDto {
  @IsString()
  id!: string;

  @IsString()
  conversation_id!: string;

  @IsString()
  sender_id!: string;

  @IsString()
  content!: string;

  @IsOptional()
  @IsIn(['user', 'assistant', 'system'])
  role?: 'user' | 'assistant' | 'system';

  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => MessageAttachmentDto)
  attachments?: MessageAttachmentDto[];

  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  visible_to_user_ids?: string[] | null;

  @IsOptional()
  @IsDateString()
  created_at?: string;

}

export class MessageAttachmentDto {
  @IsOptional()
  @IsString()
  id?: string;

  @IsOptional()
  @IsString()
  name?: string;

  @IsOptional()
  @IsNumber()
  size?: number;

  @IsOptional()
  @IsString()
  type?: string;

  @IsOptional()
  @IsString()
  url?: string;

  @IsOptional()
  @IsString()
  thumbnail_url?: string | null;

}

export class ProfileDto {
  @IsString()
  uid!: string;

  @IsOptional()
  @IsString()
  username?: string | null;

  @IsOptional()
  @IsString()
  displayName?: string | null;

  @IsOptional()
  @IsString()
  photoURL?: string | null;

  @IsOptional()
  @IsString()
  bio?: string | null;

  @IsOptional()
  @IsIn(['public', 'friends', 'private'])
  visibility?: 'public' | 'friends' | 'private';

}

export class GroupDto {
  @IsString()
  id!: string;

  @IsString()
  name!: string;

  @IsOptional()
  @IsString()
  description?: string | null;

  @IsOptional()
  @IsString()
  photo_url?: string | null;

  @IsString()
  owner_id!: string;

  @IsOptional()
  @IsNumber()
  member_count?: number;

  @IsOptional()
  @IsDateString()
  created_at?: string;

}

export class GroupMemberDto {
  @IsString()
  user_id!: string;

  @IsOptional()
  @IsString()
  display_name?: string | null;

  @IsOptional()
  @IsString()
  photo_url?: string | null;

  @IsNumber()
  auth_level!: number;

  @IsOptional()
  @ValidateNested()
  @Type(() => GroupPermissionsDto)
  permissions?: GroupPermissionsDto;

  @IsOptional()
  @IsDateString()
  joined_at?: string;

}

export class GroupPermissionsDto {
  @IsOptional()
  @IsBoolean()
  can_read?: boolean;

  @IsOptional()
  @IsBoolean()
  can_publish?: boolean;

  @IsOptional()
  @IsBoolean()
  can_manage_members?: boolean;

  @IsOptional()
  @IsBoolean()
  can_moderate?: boolean;

  @IsOptional()
  @IsBoolean()
  can_kick?: boolean;

  @IsOptional()
  @IsBoolean()
  can_ban?: boolean;

}

export class NotificationDto {
  @IsString()
  id!: string;

  @IsString()
  user_id!: string;

  @IsString()
  type!: string;

  @IsString()
  title!: string;

  @IsString()
  body!: string;

  @IsOptional()
  @IsString()
  conversation_id?: string | null;

  @IsBoolean()
  read!: boolean;

  @IsOptional()
  @IsDateString()
  created_at?: string;

}

export class RelationshipDto {
  @IsString()
  id!: string;

  @IsString()
  user_id!: string;

  @IsString()
  related_user_id!: string;

  @IsOptional()
  @IsString()
  status?: string;

  @IsOptional()
  @IsDateString()
  created_at?: string;

}

export class BoardDto {
  @IsString()
  id!: string;

  @IsString()
  user_id!: string;

  @IsString()
  name!: string;

  @IsOptional()
  @IsDateString()
  created_at?: string;

}

export class WidgetDto {
  @IsString()
  id!: string;

  @IsString()
  board_id!: string;

  @IsString()
  type!: string;

  @IsOptional()
  @IsObject()
  config?: Record<string, unknown>;

  @IsOptional()
  @IsNumber()
  position?: number;

}

export class ApiTokenDto {
  @IsString()
  id!: string;

  @IsString()
  name!: string;

  @IsOptional()
  @IsString()
  token?: string;

  @IsOptional()
  @IsDateString()
  created_at?: string;

}
